version: '3.9'

services:
  nginx:
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN=${DOMAIN}
      dockerfile: Dockerfile
    container_name: nginx_service
    networks:
      - ${NETWORK}
    ports:
      - "8080:8080" 
      - "443:443"
    restart: unless-stopped
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    #image: wordpress
    container_name: wordpress_service
    restart: unless-stopped
    networks:
      - ${NETWORK}
    volumes:
      - wp:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb_service
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=hsaadi
      - WORDPRESS_DB_PASSWORD=root123
    env_file:
      - .env 
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb_service
    restart: unless-stopped
    networks:
      - ${NETWORK}
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=hsaadi
      - MYSQL_PASSWORD=root123
    env_file:
      - .env

networks:
  inception:
    name:   ${NETWORK}
    driver: bridge

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wp

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/db

