services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wp:/var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wordpress
    networks:
      - ${NETWORK}
    restart: unless-stopped
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    networks:
      - ${NETWORK}
    restart: unless-stopped
  
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - ${NETWORK}
    restart: unless-stopped

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hsaadi/data/db
  
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hsaadi/data/wp

networks:
  inception:
    name: ${NETWORK}
    driver: bridge
