version: '3.9'

services:
  nginx:
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
      dockerfile: Dockerfile
    container_name: nginx_service
    ports:
      - "80:80" 
      - "443:443"
    restart: unless-stopped

