version: '3.9'

services:
  nginx:
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN=${DOMAIN}
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - ${NETWORK}
    ports:
      - "8080:8080" 
      - "443:443"
    restart: unless-stopped
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    image: nginx:42
    #image: wordpress
    container_name: wordpress
    restart: unless-stopped
    networks:
      - ${NETWORK}
    volumes:
      - wp:/var/www/html
    env_file:
      - .env 
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - ${NETWORK}
    volumes:
      - db:/var/lib/mysql
    hostname: mariadb_service
    env_file:
      - .env

networks:
  inception:
    name:   ${NETWORK}
    driver: bridge

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wp

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/db

