#!/bin/sh
 
if [ "$#" -ne 1 ]
then
  echo "Usage: Must supply a domain"
  exit 1
fi

SSLPATH=/etc/ssl
KEYPATH=/etc/ssl/private
CERTPATH=/etc/ssl/certs

DOMAIN=$1

openssl genrsa -out $KEYPATH/myCA.key 2048
openssl genrsa -out $KEYPATH/myCA.key 2048 -sha256 -days 365 -out $CERTPATH/myCA.pem
cp $CERTPATH/myCA.pem /ca-certificates/myCA.crt

apk update-ca-certificates

openssl genrsa -out $KEYPATH/$DOMAIN.key 2048
openssl req -new -key $KEYPATH/$DOMAIN.key -out $CERTPATH/$DOMAIN.csr

cat > $DOMAIN.ext << EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = $DOMAIN
EOF

openssl x509 -req -in $DOMAIN.csr -CA $SSLPATH/myCA.pem -CAkey $SSLPATH/myCA.key -CAcreateserial \
-out $DOMAIN.crt -days 825 -sha256 -extfile $DOMAIN.ext

